/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2017-10-14 18:04:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class collapsed_002dsidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("  <title>AdminLTE 2 | Collapsed Sidebar Layout</title>\n");
      out.write("  <!-- Tell the browser to be responsive to screen width -->\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\" name=\"viewport\">\n");
      out.write("  <!-- Bootstrap 3.3.7 -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../bower_components/bootstrap/dist/css/bootstrap.min.css\">\n");
      out.write("  <!-- Font Awesome -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../bower_components/font-awesome/css/font-awesome.min.css\">\n");
      out.write("  <!-- Ionicons -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../bower_components/Ionicons/css/ionicons.min.css\">\n");
      out.write("  <!-- Theme style -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../dist/css/AdminLTE.min.css\">\n");
      out.write("  <!-- AdminLTE Skins. Choose a skin from the css/skins\n");
      out.write("       folder instead of downloading all of them to reduce the load. -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../dist/css/skins/_all-skins.min.css\">\n");
      out.write("\n");
      out.write("  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("  <!--[if lt IE 9]>\n");
      out.write("  <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\n");
      out.write("  <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("  <![endif]-->\n");
      out.write("\n");
      out.write("  <!-- Google Font -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic\">\n");
      out.write("</head>\n");
      out.write("<!-- ADD THE CLASS sidebar-collapse TO HIDE THE SIDEBAR PRIOR TO LOADING THE SITE -->\n");
      out.write("<body class=\"hold-transition skin-blue sidebar-collapse sidebar-mini\">\n");
      out.write("<!-- Site wrapper -->\n");
      out.write("<div class=\"wrapper\">\n");
      out.write("\n");
      out.write("  <header class=\"main-header\">\n");
      out.write("    <!-- Logo -->\n");
      out.write("    <a href=\"../../index2.jsp\" class=\"logo\">\n");
      out.write("      <!-- mini logo for sidebar mini 50x50 pixels -->\n");
      out.write("      <span class=\"logo-mini\"><b>A</b>LT</span>\n");
      out.write("      <!-- logo for regular state and mobile devices -->\n");
      out.write("      <span class=\"logo-lg\"><b>Admin</b>LTE</span>\n");
      out.write("    </a>\n");
      out.write("    <!-- Header Navbar: style can be found in header.less -->\n");
      out.write("    <nav class=\"navbar navbar-static-top\">\n");
      out.write("      <!-- Sidebar toggle button-->\n");
      out.write("      <a href=\"#\" class=\"sidebar-toggle\" data-toggle=\"push-menu\" role=\"button\">\n");
      out.write("        <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("      </a>\n");
      out.write("\n");
      out.write("      <div class=\"navbar-custom-menu\">\n");
      out.write("        <ul class=\"nav navbar-nav\">\n");
      out.write("          <!-- Messages: style can be found in dropdown.less-->\n");
      out.write("          <li class=\"dropdown messages-menu\">\n");
      out.write("            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("              <i class=\"fa fa-envelope-o\"></i>\n");
      out.write("              <span class=\"label label-success\">4</span>\n");
      out.write("            </a>\n");
      out.write("            <ul class=\"dropdown-menu\">\n");
      out.write("              <li class=\"header\">You have 4 messages</li>\n");
      out.write("              <li>\n");
      out.write("                <!-- inner menu: contains the actual data -->\n");
      out.write("                <ul class=\"menu\">\n");
      out.write("                  <li><!-- start message -->\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                      <div class=\"pull-left\">\n");
      out.write("                        <img src=\"../../dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("                      </div>\n");
      out.write("                      <h4>\n");
      out.write("                        Support Team\n");
      out.write("                        <small><i class=\"fa fa-clock-o\"></i> 5 mins</small>\n");
      out.write("                      </h4>\n");
      out.write("                      <p>Why not buy a new awesome theme?</p>\n");
      out.write("                    </a>\n");
      out.write("                  </li>\n");
      out.write("                  <!-- end message -->\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"footer\"><a href=\"#\">See All Messages</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("          <!-- Notifications: style can be found in dropdown.less -->\n");
      out.write("          <li class=\"dropdown notifications-menu\">\n");
      out.write("            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("              <i class=\"fa fa-bell-o\"></i>\n");
      out.write("              <span class=\"label label-warning\">10</span>\n");
      out.write("            </a>\n");
      out.write("            <ul class=\"dropdown-menu\">\n");
      out.write("              <li class=\"header\">You have 10 notifications</li>\n");
      out.write("              <li>\n");
      out.write("                <!-- inner menu: contains the actual data -->\n");
      out.write("                <ul class=\"menu\">\n");
      out.write("                  <li>\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                      <i class=\"fa fa-users text-aqua\"></i> 5 new members joined today\n");
      out.write("                    </a>\n");
      out.write("                  </li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"footer\"><a href=\"#\">View all</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("          <!-- Tasks: style can be found in dropdown.less -->\n");
      out.write("          <li class=\"dropdown tasks-menu\">\n");
      out.write("            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("              <i class=\"fa fa-flag-o\"></i>\n");
      out.write("              <span class=\"label label-danger\">9</span>\n");
      out.write("            </a>\n");
      out.write("            <ul class=\"dropdown-menu\">\n");
      out.write("              <li class=\"header\">You have 9 tasks</li>\n");
      out.write("              <li>\n");
      out.write("                <!-- inner menu: contains the actual data -->\n");
      out.write("                <ul class=\"menu\">\n");
      out.write("                  <li><!-- Task item -->\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                      <h3>\n");
      out.write("                        Design some buttons\n");
      out.write("                        <small class=\"pull-right\">20%</small>\n");
      out.write("                      </h3>\n");
      out.write("                      <div class=\"progress xs\">\n");
      out.write("                        <div class=\"progress-bar progress-bar-aqua\" style=\"width: 20%\" role=\"progressbar\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">\n");
      out.write("                          <span class=\"sr-only\">20% Complete</span>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </a>\n");
      out.write("                  </li>\n");
      out.write("                  <!-- end task item -->\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"footer\">\n");
      out.write("                <a href=\"#\">View all tasks</a>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("          <!-- User Account: style can be found in dropdown.less -->\n");
      out.write("          <li class=\"dropdown user user-menu\">\n");
      out.write("            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("              <img src=\"../../dist/img/user2-160x160.jpg\" class=\"user-image\" alt=\"User Image\">\n");
      out.write("              <span class=\"hidden-xs\">Alexander Pierce</span>\n");
      out.write("            </a>\n");
      out.write("            <ul class=\"dropdown-menu\">\n");
      out.write("              <!-- User image -->\n");
      out.write("              <li class=\"user-header\">\n");
      out.write("                <img src=\"../../dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("\n");
      out.write("                <p>\n");
      out.write("                  Alexander Pierce - Web Developer\n");
      out.write("                  <small>Member since Nov. 2012</small>\n");
      out.write("                </p>\n");
      out.write("              </li>\n");
      out.write("              <!-- Menu Body -->\n");
      out.write("              <li class=\"user-body\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                  <div class=\"col-xs-4 text-center\">\n");
      out.write("                    <a href=\"#\">Followers</a>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-xs-4 text-center\">\n");
      out.write("                    <a href=\"#\">Sales</a>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-xs-4 text-center\">\n");
      out.write("                    <a href=\"#\">Friends</a>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- /.row -->\n");
      out.write("              </li>\n");
      out.write("              <!-- Menu Footer-->\n");
      out.write("              <li class=\"user-footer\">\n");
      out.write("                <div class=\"pull-left\">\n");
      out.write("                  <a href=\"#\" class=\"btn btn-default btn-flat\">Profile</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pull-right\">\n");
      out.write("                  <a href=\"#\" class=\"btn btn-default btn-flat\">Sign out</a>\n");
      out.write("                </div>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("          <!-- Control Sidebar Toggle Button -->\n");
      out.write("          <li>\n");
      out.write("            <a href=\"#\" data-toggle=\"control-sidebar\"><i class=\"fa fa-gears\"></i></a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("  <!-- =============================================== -->\n");
      out.write("\n");
      out.write("  <!-- Left side column. contains the sidebar -->\n");
      out.write("  <aside class=\"main-sidebar\">\n");
      out.write("    <!-- sidebar: style can be found in sidebar.less -->\n");
      out.write("    <section class=\"sidebar\">\n");
      out.write("      <!-- Sidebar user panel -->\n");
      out.write("      <div class=\"user-panel\">\n");
      out.write("        <div class=\"pull-left image\">\n");
      out.write("          <img src=\"../../dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"pull-left info\">\n");
      out.write("          <p>Alexander Pierce</p>\n");
      out.write("          <a href=\"#\"><i class=\"fa fa-circle text-success\"></i> Online</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <!-- search form -->\n");
      out.write("      <form action=\"#\" method=\"get\" class=\"sidebar-form\">\n");
      out.write("        <div class=\"input-group\">\n");
      out.write("          <input type=\"text\" name=\"q\" class=\"form-control\" placeholder=\"Search...\">\n");
      out.write("              <span class=\"input-group-btn\">\n");
      out.write("                <button type=\"submit\" name=\"search\" id=\"search-btn\" class=\"btn btn-flat\"><i class=\"fa fa-search\"></i>\n");
      out.write("                </button>\n");
      out.write("              </span>\n");
      out.write("        </div>\n");
      out.write("      </form>\n");
      out.write("      <!-- /.search form -->\n");
      out.write("      <!-- sidebar menu: : style can be found in sidebar.less -->\n");
      out.write("      <ul class=\"sidebar-menu\" data-widget=\"tree\">\n");
      out.write("        <li class=\"header\">MAIN NAVIGATION</li>\n");
      out.write("        <li class=\"treeview\">\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <i class=\"fa fa-dashboard\"></i> <span>Dashboard</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"treeview-menu\">\n");
      out.write("            <li><a href=\"../../index.jsp\"><i class=\"fa fa-circle-o\"></i> Dashboard v1</a></li>\n");
      out.write("            <li><a href=\"../../index2.jsp\"><i class=\"fa fa-circle-o\"></i> Dashboard v2</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"treeview active\">\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <i class=\"fa fa-files-o\"></i>\n");
      out.write("            <span>Layout Options</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <span class=\"label label-primary pull-right\">4</span>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"treeview-menu\">\n");
      out.write("            <li><a href=\"top-nav.jsp\"><i class=\"fa fa-circle-o\"></i> Top Navigation</a></li>\n");
      out.write("            <li><a href=\"boxed.jsp\"><i class=\"fa fa-circle-o\"></i> Boxed</a></li>\n");
      out.write("            <li><a href=\"fixed.jsp\"><i class=\"fa fa-circle-o\"></i> Fixed</a></li>\n");
      out.write("            <li class=\"active\"><a href=\"collapsed-sidebar.jsp\"><i class=\"fa fa-circle-o\"></i> Collapsed Sidebar</a>\n");
      out.write("            </li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("          <a href=\"../widgets.jsp\">\n");
      out.write("            <i class=\"fa fa-th\"></i> <span>Widgets</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <small class=\"label pull-right bg-green\">new</small>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"treeview\">\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <i class=\"fa fa-pie-chart\"></i>\n");
      out.write("            <span>Charts</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"treeview-menu\">\n");
      out.write("            <li><a href=\"../charts/chartjs.jsp\"><i class=\"fa fa-circle-o\"></i> ChartJS</a></li>\n");
      out.write("            <li><a href=\"../charts/morris.jsp\"><i class=\"fa fa-circle-o\"></i> Morris</a></li>\n");
      out.write("            <li><a href=\"../charts/flot.jsp\"><i class=\"fa fa-circle-o\"></i> Flot</a></li>\n");
      out.write("            <li><a href=\"../charts/inline.jsp\"><i class=\"fa fa-circle-o\"></i> Inline charts</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"treeview\">\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <i class=\"fa fa-laptop\"></i>\n");
      out.write("            <span>UI Elements</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"treeview-menu\">\n");
      out.write("            <li><a href=\"../UI/general.jsp\"><i class=\"fa fa-circle-o\"></i> General</a></li>\n");
      out.write("            <li><a href=\"../UI/icons.jsp\"><i class=\"fa fa-circle-o\"></i> Icons</a></li>\n");
      out.write("            <li><a href=\"../UI/buttons.jsp\"><i class=\"fa fa-circle-o\"></i> Buttons</a></li>\n");
      out.write("            <li><a href=\"../UI/sliders.jsp\"><i class=\"fa fa-circle-o\"></i> Sliders</a></li>\n");
      out.write("            <li><a href=\"../UI/timeline.jsp\"><i class=\"fa fa-circle-o\"></i> Timeline</a></li>\n");
      out.write("            <li><a href=\"../UI/modals.jsp\"><i class=\"fa fa-circle-o\"></i> Modals</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"treeview\">\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <i class=\"fa fa-edit\"></i> <span>Forms</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"treeview-menu\">\n");
      out.write("            <li><a href=\"../forms/general.jsp\"><i class=\"fa fa-circle-o\"></i> General Elements</a></li>\n");
      out.write("            <li><a href=\"../forms/advanced.jsp\"><i class=\"fa fa-circle-o\"></i> Advanced Elements</a></li>\n");
      out.write("            <li><a href=\"../forms/editors.jsp\"><i class=\"fa fa-circle-o\"></i> Editors</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"treeview\">\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <i class=\"fa fa-table\"></i> <span>Tables</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"treeview-menu\">\n");
      out.write("            <li><a href=\"../tables/simple.jsp\"><i class=\"fa fa-circle-o\"></i> Simple tables</a></li>\n");
      out.write("            <li><a href=\"../tables/data.jsp\"><i class=\"fa fa-circle-o\"></i> Data tables</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("          <a href=\"../calendar.jsp\">\n");
      out.write("            <i class=\"fa fa-calendar\"></i> <span>Calendar</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <small class=\"label pull-right bg-red\">3</small>\n");
      out.write("              <small class=\"label pull-right bg-blue\">17</small>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("          <a href=\"../mailbox/mailbox.jsp\">\n");
      out.write("            <i class=\"fa fa-envelope\"></i> <span>Mailbox</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <small class=\"label pull-right bg-yellow\">12</small>\n");
      out.write("              <small class=\"label pull-right bg-green\">16</small>\n");
      out.write("              <small class=\"label pull-right bg-red\">5</small>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"treeview\">\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <i class=\"fa fa-folder\"></i> <span>Examples</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"treeview-menu\">\n");
      out.write("            <li><a href=\"../examples/invoice.jsp\"><i class=\"fa fa-circle-o\"></i> Invoice</a></li>\n");
      out.write("            <li><a href=\"../examples/profile.jsp\"><i class=\"fa fa-circle-o\"></i> Profile</a></li>\n");
      out.write("            <li><a href=\"../examples/login.jsp\"><i class=\"fa fa-circle-o\"></i> Login</a></li>\n");
      out.write("            <li><a href=\"../examples/register.jsp\"><i class=\"fa fa-circle-o\"></i> Register</a></li>\n");
      out.write("            <li><a href=\"../examples/lockscreen.jsp\"><i class=\"fa fa-circle-o\"></i> Lockscreen</a></li>\n");
      out.write("            <li><a href=\"../examples/404.jsp\"><i class=\"fa fa-circle-o\"></i> 404 Error</a></li>\n");
      out.write("            <li><a href=\"../examples/500.jsp\"><i class=\"fa fa-circle-o\"></i> 500 Error</a></li>\n");
      out.write("            <li><a href=\"../examples/blank.jsp\"><i class=\"fa fa-circle-o\"></i> Blank Page</a></li>\n");
      out.write("            <li><a href=\"../examples/pace.jsp\"><i class=\"fa fa-circle-o\"></i> Pace Page</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"treeview\">\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <i class=\"fa fa-share\"></i> <span>Multilevel</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"treeview-menu\">\n");
      out.write("            <li><a href=\"#\"><i class=\"fa fa-circle-o\"></i> Level One</a></li>\n");
      out.write("            <li class=\"treeview\">\n");
      out.write("              <a href=\"#\"><i class=\"fa fa-circle-o\"></i> Level One\n");
      out.write("                <span class=\"pull-right-container\">\n");
      out.write("                  <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("                </span>\n");
      out.write("              </a>\n");
      out.write("              <ul class=\"treeview-menu\">\n");
      out.write("                <li><a href=\"#\"><i class=\"fa fa-circle-o\"></i> Level Two</a></li>\n");
      out.write("                <li class=\"treeview\">\n");
      out.write("                  <a href=\"#\"><i class=\"fa fa-circle-o\"></i> Level Two\n");
      out.write("                    <span class=\"pull-right-container\">\n");
      out.write("                      <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("                    </span>\n");
      out.write("                  </a>\n");
      out.write("                  <ul class=\"treeview-menu\">\n");
      out.write("                    <li><a href=\"#\"><i class=\"fa fa-circle-o\"></i> Level Three</a></li>\n");
      out.write("                    <li><a href=\"#\"><i class=\"fa fa-circle-o\"></i> Level Three</a></li>\n");
      out.write("                  </ul>\n");
      out.write("                </li>\n");
      out.write("              </ul>\n");
      out.write("            </li>\n");
      out.write("            <li><a href=\"#\"><i class=\"fa fa-circle-o\"></i> Level One</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li><a href=\"https://adminlte.io/docs\"><i class=\"fa fa-book\"></i> <span>Documentation</span></a></li>\n");
      out.write("        <li class=\"header\">LABELS</li>\n");
      out.write("        <li><a href=\"#\"><i class=\"fa fa-circle-o text-red\"></i> <span>Important</span></a></li>\n");
      out.write("        <li><a href=\"#\"><i class=\"fa fa-circle-o text-yellow\"></i> <span>Warning</span></a></li>\n");
      out.write("        <li><a href=\"#\"><i class=\"fa fa-circle-o text-aqua\"></i> <span>Information</span></a></li>\n");
      out.write("      </ul>\n");
      out.write("    </section>\n");
      out.write("    <!-- /.sidebar -->\n");
      out.write("  </aside>\n");
      out.write("\n");
      out.write("  <!-- =============================================== -->\n");
      out.write("\n");
      out.write("  <!-- Content Wrapper. Contains page content -->\n");
      out.write("  <div class=\"content-wrapper\">\n");
      out.write("    <!-- Content Header (Page header) -->\n");
      out.write("    <section class=\"content-header\">\n");
      out.write("      <h1>\n");
      out.write("        Sidebar Collapsed\n");
      out.write("        <small>Layout with collapsed sidebar on load</small>\n");
      out.write("      </h1>\n");
      out.write("      <ol class=\"breadcrumb\">\n");
      out.write("        <li><a href=\"#\"><i class=\"fa fa-dashboard\"></i> Home</a></li>\n");
      out.write("        <li><a href=\"#\">Layout</a></li>\n");
      out.write("        <li class=\"active\">Collapsed Sidebar</li>\n");
      out.write("      </ol>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Main content -->\n");
      out.write("    <section class=\"content\">\n");
      out.write("      <div class=\"callout callout-info\">\n");
      out.write("        <h4>Tip!</h4>\n");
      out.write("\n");
      out.write("        <p>Add the sidebar-collapse class to the body tag to get this layout. You should combine this option with a\n");
      out.write("          fixed layout if you have a long sidebar. Doing that will prevent your page content from getting stretched\n");
      out.write("          vertically.</p>\n");
      out.write("      </div>\n");
      out.write("      <!-- Default box -->\n");
      out.write("      <div class=\"box\">\n");
      out.write("        <div class=\"box-header with-border\">\n");
      out.write("          <h3 class=\"box-title\">Title</h3>\n");
      out.write("\n");
      out.write("          <div class=\"box-tools pull-right\">\n");
      out.write("            <button type=\"button\" class=\"btn btn-box-tool\" data-widget=\"collapse\" data-toggle=\"tooltip\" title=\"Collapse\">\n");
      out.write("              <i class=\"fa fa-minus\"></i></button>\n");
      out.write("            <button type=\"button\" class=\"btn btn-box-tool\" data-widget=\"remove\" data-toggle=\"tooltip\" title=\"Remove\">\n");
      out.write("              <i class=\"fa fa-times\"></i></button>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"box-body\">\n");
      out.write("          Start creating your amazing application!\n");
      out.write("        </div>\n");
      out.write("        <!-- /.box-body -->\n");
      out.write("        <div class=\"box-footer\">\n");
      out.write("          Footer\n");
      out.write("        </div>\n");
      out.write("        <!-- /.box-footer-->\n");
      out.write("      </div>\n");
      out.write("      <!-- /.box -->\n");
      out.write("    </section>\n");
      out.write("    <!-- /.content -->\n");
      out.write("  </div>\n");
      out.write("  <!-- /.content-wrapper -->\n");
      out.write("\n");
      out.write("  <footer class=\"main-footer\">\n");
      out.write("    <div class=\"pull-right hidden-xs\">\n");
      out.write("      <b>Version</b> 2.4.0\n");
      out.write("    </div>\n");
      out.write("    <strong>Copyright &copy; 2014-2016 <a href=\"https://adminlte.io\">Almsaeed Studio</a>.</strong> All rights\n");
      out.write("    reserved.\n");
      out.write("  </footer>\n");
      out.write("\n");
      out.write("  <!-- Control Sidebar -->\n");
      out.write("  <aside class=\"control-sidebar control-sidebar-dark\">\n");
      out.write("    <!-- Create the tabs -->\n");
      out.write("    <ul class=\"nav nav-tabs nav-justified control-sidebar-tabs\">\n");
      out.write("      <li><a href=\"#control-sidebar-home-tab\" data-toggle=\"tab\"><i class=\"fa fa-home\"></i></a></li>\n");
      out.write("      <li><a href=\"#control-sidebar-settings-tab\" data-toggle=\"tab\"><i class=\"fa fa-gears\"></i></a></li>\n");
      out.write("    </ul>\n");
      out.write("    <!-- Tab panes -->\n");
      out.write("    <div class=\"tab-content\">\n");
      out.write("      <!-- Home tab content -->\n");
      out.write("      <div class=\"tab-pane\" id=\"control-sidebar-home-tab\">\n");
      out.write("        <h3 class=\"control-sidebar-heading\">Recent Activity</h3>\n");
      out.write("        <ul class=\"control-sidebar-menu\">\n");
      out.write("          <li>\n");
      out.write("            <a href=\"javascript:void(0)\">\n");
      out.write("              <i class=\"menu-icon fa fa-birthday-cake bg-red\"></i>\n");
      out.write("\n");
      out.write("              <div class=\"menu-info\">\n");
      out.write("                <h4 class=\"control-sidebar-subheading\">Langdon's Birthday</h4>\n");
      out.write("\n");
      out.write("                <p>Will be 23 on April 24th</p>\n");
      out.write("              </div>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"javascript:void(0)\">\n");
      out.write("              <i class=\"menu-icon fa fa-user bg-yellow\"></i>\n");
      out.write("\n");
      out.write("              <div class=\"menu-info\">\n");
      out.write("                <h4 class=\"control-sidebar-subheading\">Frodo Updated His Profile</h4>\n");
      out.write("\n");
      out.write("                <p>New phone +1(800)555-1234</p>\n");
      out.write("              </div>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"javascript:void(0)\">\n");
      out.write("              <i class=\"menu-icon fa fa-envelope-o bg-light-blue\"></i>\n");
      out.write("\n");
      out.write("              <div class=\"menu-info\">\n");
      out.write("                <h4 class=\"control-sidebar-subheading\">Nora Joined Mailing List</h4>\n");
      out.write("\n");
      out.write("                <p>nora@example.com</p>\n");
      out.write("              </div>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"javascript:void(0)\">\n");
      out.write("              <i class=\"menu-icon fa fa-file-code-o bg-green\"></i>\n");
      out.write("\n");
      out.write("              <div class=\"menu-info\">\n");
      out.write("                <h4 class=\"control-sidebar-subheading\">Cron Job 254 Executed</h4>\n");
      out.write("\n");
      out.write("                <p>Execution time 5 seconds</p>\n");
      out.write("              </div>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("        <!-- /.control-sidebar-menu -->\n");
      out.write("\n");
      out.write("        <h3 class=\"control-sidebar-heading\">Tasks Progress</h3>\n");
      out.write("        <ul class=\"control-sidebar-menu\">\n");
      out.write("          <li>\n");
      out.write("            <a href=\"javascript:void(0)\">\n");
      out.write("              <h4 class=\"control-sidebar-subheading\">\n");
      out.write("                Custom Template Design\n");
      out.write("                <span class=\"label label-danger pull-right\">70%</span>\n");
      out.write("              </h4>\n");
      out.write("\n");
      out.write("              <div class=\"progress progress-xxs\">\n");
      out.write("                <div class=\"progress-bar progress-bar-danger\" style=\"width: 70%\"></div>\n");
      out.write("              </div>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"javascript:void(0)\">\n");
      out.write("              <h4 class=\"control-sidebar-subheading\">\n");
      out.write("                Update Resume\n");
      out.write("                <span class=\"label label-success pull-right\">95%</span>\n");
      out.write("              </h4>\n");
      out.write("\n");
      out.write("              <div class=\"progress progress-xxs\">\n");
      out.write("                <div class=\"progress-bar progress-bar-success\" style=\"width: 95%\"></div>\n");
      out.write("              </div>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"javascript:void(0)\">\n");
      out.write("              <h4 class=\"control-sidebar-subheading\">\n");
      out.write("                Laravel Integration\n");
      out.write("                <span class=\"label label-warning pull-right\">50%</span>\n");
      out.write("              </h4>\n");
      out.write("\n");
      out.write("              <div class=\"progress progress-xxs\">\n");
      out.write("                <div class=\"progress-bar progress-bar-warning\" style=\"width: 50%\"></div>\n");
      out.write("              </div>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"javascript:void(0)\">\n");
      out.write("              <h4 class=\"control-sidebar-subheading\">\n");
      out.write("                Back End Framework\n");
      out.write("                <span class=\"label label-primary pull-right\">68%</span>\n");
      out.write("              </h4>\n");
      out.write("\n");
      out.write("              <div class=\"progress progress-xxs\">\n");
      out.write("                <div class=\"progress-bar progress-bar-primary\" style=\"width: 68%\"></div>\n");
      out.write("              </div>\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("        <!-- /.control-sidebar-menu -->\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("      <!-- /.tab-pane -->\n");
      out.write("      <!-- Stats tab content -->\n");
      out.write("      <div class=\"tab-pane\" id=\"control-sidebar-stats-tab\">Stats Tab Content</div>\n");
      out.write("      <!-- /.tab-pane -->\n");
      out.write("      <!-- Settings tab content -->\n");
      out.write("      <div class=\"tab-pane\" id=\"control-sidebar-settings-tab\">\n");
      out.write("        <form method=\"post\">\n");
      out.write("          <h3 class=\"control-sidebar-heading\">General Settings</h3>\n");
      out.write("\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label class=\"control-sidebar-subheading\">\n");
      out.write("              Report panel usage\n");
      out.write("              <input type=\"checkbox\" class=\"pull-right\" checked>\n");
      out.write("            </label>\n");
      out.write("\n");
      out.write("            <p>\n");
      out.write("              Some information about this general settings option\n");
      out.write("            </p>\n");
      out.write("          </div>\n");
      out.write("          <!-- /.form-group -->\n");
      out.write("\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label class=\"control-sidebar-subheading\">\n");
      out.write("              Allow mail redirect\n");
      out.write("              <input type=\"checkbox\" class=\"pull-right\" checked>\n");
      out.write("            </label>\n");
      out.write("\n");
      out.write("            <p>\n");
      out.write("              Other sets of options are available\n");
      out.write("            </p>\n");
      out.write("          </div>\n");
      out.write("          <!-- /.form-group -->\n");
      out.write("\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label class=\"control-sidebar-subheading\">\n");
      out.write("              Expose author name in posts\n");
      out.write("              <input type=\"checkbox\" class=\"pull-right\" checked>\n");
      out.write("            </label>\n");
      out.write("\n");
      out.write("            <p>\n");
      out.write("              Allow the user to show his name in blog posts\n");
      out.write("            </p>\n");
      out.write("          </div>\n");
      out.write("          <!-- /.form-group -->\n");
      out.write("\n");
      out.write("          <h3 class=\"control-sidebar-heading\">Chat Settings</h3>\n");
      out.write("\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label class=\"control-sidebar-subheading\">\n");
      out.write("              Show me as online\n");
      out.write("              <input type=\"checkbox\" class=\"pull-right\" checked>\n");
      out.write("            </label>\n");
      out.write("          </div>\n");
      out.write("          <!-- /.form-group -->\n");
      out.write("\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label class=\"control-sidebar-subheading\">\n");
      out.write("              Turn off notifications\n");
      out.write("              <input type=\"checkbox\" class=\"pull-right\">\n");
      out.write("            </label>\n");
      out.write("          </div>\n");
      out.write("          <!-- /.form-group -->\n");
      out.write("\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label class=\"control-sidebar-subheading\">\n");
      out.write("              Delete chat history\n");
      out.write("              <a href=\"javascript:void(0)\" class=\"text-red pull-right\"><i class=\"fa fa-trash-o\"></i></a>\n");
      out.write("            </label>\n");
      out.write("          </div>\n");
      out.write("          <!-- /.form-group -->\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("      <!-- /.tab-pane -->\n");
      out.write("    </div>\n");
      out.write("  </aside>\n");
      out.write("  <!-- /.control-sidebar -->\n");
      out.write("  <!-- Add the sidebar's background. This div must be placed\n");
      out.write("       immediately after the control sidebar -->\n");
      out.write("  <div class=\"control-sidebar-bg\"></div>\n");
      out.write("</div>\n");
      out.write("<!-- ./wrapper -->\n");
      out.write("\n");
      out.write("<!-- jQuery 3 -->\n");
      out.write("<script src=\"../../bower_components/jquery/dist/jquery.min.js\"></script>\n");
      out.write("<!-- Bootstrap 3.3.7 -->\n");
      out.write("<script src=\"../../bower_components/bootstrap/dist/js/bootstrap.min.js\"></script>\n");
      out.write("<!-- SlimScroll -->\n");
      out.write("<script src=\"../../bower_components/jquery-slimscroll/jquery.slimscroll.min.js\"></script>\n");
      out.write("<!-- FastClick -->\n");
      out.write("<script src=\"../../bower_components/fastclick/lib/fastclick.js\"></script>\n");
      out.write("<!-- AdminLTE App -->\n");
      out.write("<script src=\"../../dist/js/adminlte.min.js\"></script>\n");
      out.write("<!-- AdminLTE for demo purposes -->\n");
      out.write("<script src=\"../../dist/js/demo.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
