/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2017-10-14 18:01:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class top_002dnav_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("  <title>AdminLTE 2 | Top Navigation</title>\n");
      out.write("  <!-- Tell the browser to be responsive to screen width -->\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\" name=\"viewport\">\n");
      out.write("  <!-- Bootstrap 3.3.7 -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../bower_components/bootstrap/dist/css/bootstrap.min.css\">\n");
      out.write("  <!-- Font Awesome -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../bower_components/font-awesome/css/font-awesome.min.css\">\n");
      out.write("  <!-- Ionicons -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../bower_components/Ionicons/css/ionicons.min.css\">\n");
      out.write("  <!-- Theme style -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../dist/css/AdminLTE.min.css\">\n");
      out.write("  <!-- AdminLTE Skins. Choose a skin from the css/skins\n");
      out.write("       folder instead of downloading all of them to reduce the load. -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../dist/css/skins/_all-skins.min.css\">\n");
      out.write("\n");
      out.write("  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("  <!--[if lt IE 9]>\n");
      out.write("  <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\n");
      out.write("  <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("  <![endif]-->\n");
      out.write("\n");
      out.write("  <!-- Google Font -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic\">\n");
      out.write("</head>\n");
      out.write("<!-- ADD THE CLASS layout-top-nav TO REMOVE THE SIDEBAR. -->\n");
      out.write("<body class=\"hold-transition skin-blue layout-top-nav\">\n");
      out.write("<div class=\"wrapper\">\n");
      out.write("\n");
      out.write("  <header class=\"main-header\">\n");
      out.write("    <nav class=\"navbar navbar-static-top\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"navbar-header\">\n");
      out.write("          <a href=\"../../index2.jsp\" class=\"navbar-brand\"><b>Admin</b>LTE</a>\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar-collapse\">\n");
      out.write("            <i class=\"fa fa-bars\"></i>\n");
      out.write("          </button>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("        <div class=\"collapse navbar-collapse pull-left\" id=\"navbar-collapse\">\n");
      out.write("          <ul class=\"nav navbar-nav\">\n");
      out.write("            <li class=\"active\"><a href=\"#\">Link <span class=\"sr-only\">(current)</span></a></li>\n");
      out.write("            <li><a href=\"#\">Link</a></li>\n");
      out.write("            <li class=\"dropdown\">\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown <span class=\"caret\"></span></a>\n");
      out.write("              <ul class=\"dropdown-menu\" role=\"menu\">\n");
      out.write("                <li><a href=\"#\">Action</a></li>\n");
      out.write("                <li><a href=\"#\">Another action</a></li>\n");
      out.write("                <li><a href=\"#\">Something else here</a></li>\n");
      out.write("                <li class=\"divider\"></li>\n");
      out.write("                <li><a href=\"#\">Separated link</a></li>\n");
      out.write("                <li class=\"divider\"></li>\n");
      out.write("                <li><a href=\"#\">One more separated link</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </li>\n");
      out.write("          </ul>\n");
      out.write("          <form class=\"navbar-form navbar-left\" role=\"search\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"navbar-search-input\" placeholder=\"Search\">\n");
      out.write("            </div>\n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("        <!-- /.navbar-collapse -->\n");
      out.write("        <!-- Navbar Right Menu -->\n");
      out.write("        <div class=\"navbar-custom-menu\">\n");
      out.write("          <ul class=\"nav navbar-nav\">\n");
      out.write("            <!-- Messages: style can be found in dropdown.less-->\n");
      out.write("            <li class=\"dropdown messages-menu\">\n");
      out.write("              <!-- Menu toggle button -->\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("                <i class=\"fa fa-envelope-o\"></i>\n");
      out.write("                <span class=\"label label-success\">4</span>\n");
      out.write("              </a>\n");
      out.write("              <ul class=\"dropdown-menu\">\n");
      out.write("                <li class=\"header\">You have 4 messages</li>\n");
      out.write("                <li>\n");
      out.write("                  <!-- inner menu: contains the messages -->\n");
      out.write("                  <ul class=\"menu\">\n");
      out.write("                    <li><!-- start message -->\n");
      out.write("                      <a href=\"#\">\n");
      out.write("                        <div class=\"pull-left\">\n");
      out.write("                          <!-- User Image -->\n");
      out.write("                          <img src=\"../../dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("                        </div>\n");
      out.write("                        <!-- Message title and timestamp -->\n");
      out.write("                        <h4>\n");
      out.write("                          Support Team\n");
      out.write("                          <small><i class=\"fa fa-clock-o\"></i> 5 mins</small>\n");
      out.write("                        </h4>\n");
      out.write("                        <!-- The message -->\n");
      out.write("                        <p>Why not buy a new awesome theme?</p>\n");
      out.write("                      </a>\n");
      out.write("                    </li>\n");
      out.write("                    <!-- end message -->\n");
      out.write("                  </ul>\n");
      out.write("                  <!-- /.menu -->\n");
      out.write("                </li>\n");
      out.write("                <li class=\"footer\"><a href=\"#\">See All Messages</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </li>\n");
      out.write("            <!-- /.messages-menu -->\n");
      out.write("\n");
      out.write("            <!-- Notifications Menu -->\n");
      out.write("            <li class=\"dropdown notifications-menu\">\n");
      out.write("              <!-- Menu toggle button -->\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("                <i class=\"fa fa-bell-o\"></i>\n");
      out.write("                <span class=\"label label-warning\">10</span>\n");
      out.write("              </a>\n");
      out.write("              <ul class=\"dropdown-menu\">\n");
      out.write("                <li class=\"header\">You have 10 notifications</li>\n");
      out.write("                <li>\n");
      out.write("                  <!-- Inner Menu: contains the notifications -->\n");
      out.write("                  <ul class=\"menu\">\n");
      out.write("                    <li><!-- start notification -->\n");
      out.write("                      <a href=\"#\">\n");
      out.write("                        <i class=\"fa fa-users text-aqua\"></i> 5 new members joined today\n");
      out.write("                      </a>\n");
      out.write("                    </li>\n");
      out.write("                    <!-- end notification -->\n");
      out.write("                  </ul>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"footer\"><a href=\"#\">View all</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </li>\n");
      out.write("            <!-- Tasks Menu -->\n");
      out.write("            <li class=\"dropdown tasks-menu\">\n");
      out.write("              <!-- Menu Toggle Button -->\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("                <i class=\"fa fa-flag-o\"></i>\n");
      out.write("                <span class=\"label label-danger\">9</span>\n");
      out.write("              </a>\n");
      out.write("              <ul class=\"dropdown-menu\">\n");
      out.write("                <li class=\"header\">You have 9 tasks</li>\n");
      out.write("                <li>\n");
      out.write("                  <!-- Inner menu: contains the tasks -->\n");
      out.write("                  <ul class=\"menu\">\n");
      out.write("                    <li><!-- Task item -->\n");
      out.write("                      <a href=\"#\">\n");
      out.write("                        <!-- Task title and progress text -->\n");
      out.write("                        <h3>\n");
      out.write("                          Design some buttons\n");
      out.write("                          <small class=\"pull-right\">20%</small>\n");
      out.write("                        </h3>\n");
      out.write("                        <!-- The progress bar -->\n");
      out.write("                        <div class=\"progress xs\">\n");
      out.write("                          <!-- Change the css width attribute to simulate progress -->\n");
      out.write("                          <div class=\"progress-bar progress-bar-aqua\" style=\"width: 20%\" role=\"progressbar\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">\n");
      out.write("                            <span class=\"sr-only\">20% Complete</span>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("                      </a>\n");
      out.write("                    </li>\n");
      out.write("                    <!-- end task item -->\n");
      out.write("                  </ul>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"footer\">\n");
      out.write("                  <a href=\"#\">View all tasks</a>\n");
      out.write("                </li>\n");
      out.write("              </ul>\n");
      out.write("            </li>\n");
      out.write("            <!-- User Account Menu -->\n");
      out.write("            <li class=\"dropdown user user-menu\">\n");
      out.write("              <!-- Menu Toggle Button -->\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("                <!-- The user image in the navbar-->\n");
      out.write("                <img src=\"../../dist/img/user2-160x160.jpg\" class=\"user-image\" alt=\"User Image\">\n");
      out.write("                <!-- hidden-xs hides the username on small devices so only the image appears. -->\n");
      out.write("                <span class=\"hidden-xs\">Alexander Pierce</span>\n");
      out.write("              </a>\n");
      out.write("              <ul class=\"dropdown-menu\">\n");
      out.write("                <!-- The user image in the menu -->\n");
      out.write("                <li class=\"user-header\">\n");
      out.write("                  <img src=\"../../dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("\n");
      out.write("                  <p>\n");
      out.write("                    Alexander Pierce - Web Developer\n");
      out.write("                    <small>Member since Nov. 2012</small>\n");
      out.write("                  </p>\n");
      out.write("                </li>\n");
      out.write("                <!-- Menu Body -->\n");
      out.write("                <li class=\"user-body\">\n");
      out.write("                  <div class=\"row\">\n");
      out.write("                    <div class=\"col-xs-4 text-center\">\n");
      out.write("                      <a href=\"#\">Followers</a>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-xs-4 text-center\">\n");
      out.write("                      <a href=\"#\">Sales</a>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-xs-4 text-center\">\n");
      out.write("                      <a href=\"#\">Friends</a>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <!-- /.row -->\n");
      out.write("                </li>\n");
      out.write("                <!-- Menu Footer-->\n");
      out.write("                <li class=\"user-footer\">\n");
      out.write("                  <div class=\"pull-left\">\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default btn-flat\">Profile</a>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"pull-right\">\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default btn-flat\">Sign out</a>\n");
      out.write("                  </div>\n");
      out.write("                </li>\n");
      out.write("              </ul>\n");
      out.write("            </li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("        <!-- /.navbar-custom-menu -->\n");
      out.write("      </div>\n");
      out.write("      <!-- /.container-fluid -->\n");
      out.write("    </nav>\n");
      out.write("  </header>\n");
      out.write("  <!-- Full Width Column -->\n");
      out.write("  <div class=\"content-wrapper\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <!-- Content Header (Page header) -->\n");
      out.write("      <section class=\"content-header\">\n");
      out.write("        <h1>\n");
      out.write("          Top Navigation\n");
      out.write("          <small>Example 2.0</small>\n");
      out.write("        </h1>\n");
      out.write("        <ol class=\"breadcrumb\">\n");
      out.write("          <li><a href=\"#\"><i class=\"fa fa-dashboard\"></i> Home</a></li>\n");
      out.write("          <li><a href=\"#\">Layout</a></li>\n");
      out.write("          <li class=\"active\">Top Navigation</li>\n");
      out.write("        </ol>\n");
      out.write("      </section>\n");
      out.write("\n");
      out.write("      <!-- Main content -->\n");
      out.write("      <section class=\"content\">\n");
      out.write("        <div class=\"callout callout-info\">\n");
      out.write("          <h4>Tip!</h4>\n");
      out.write("\n");
      out.write("          <p>Add the layout-top-nav class to the body tag to get this layout. This feature can also be used with a\n");
      out.write("            sidebar! So use this class if you want to remove the custom dropdown menus from the navbar and use regular\n");
      out.write("            links instead.</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"callout callout-danger\">\n");
      out.write("          <h4>Warning!</h4>\n");
      out.write("\n");
      out.write("          <p>The construction of this layout differs from the normal one. In other words, the HTML markup of the navbar\n");
      out.write("            and the content will slightly differ than that of the normal layout.</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"box box-default\">\n");
      out.write("          <div class=\"box-header with-border\">\n");
      out.write("            <h3 class=\"box-title\">Blank Box</h3>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"box-body\">\n");
      out.write("            The great content goes here\n");
      out.write("          </div>\n");
      out.write("          <!-- /.box-body -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /.box -->\n");
      out.write("      </section>\n");
      out.write("      <!-- /.content -->\n");
      out.write("    </div>\n");
      out.write("    <!-- /.container -->\n");
      out.write("  </div>\n");
      out.write("  <!-- /.content-wrapper -->\n");
      out.write("  <footer class=\"main-footer\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"pull-right hidden-xs\">\n");
      out.write("        <b>Version</b> 2.4.0\n");
      out.write("      </div>\n");
      out.write("      <strong>Copyright &copy; 2014-2016 <a href=\"https://adminlte.io\">Almsaeed Studio</a>.</strong> All rights\n");
      out.write("      reserved.\n");
      out.write("    </div>\n");
      out.write("    <!-- /.container -->\n");
      out.write("  </footer>\n");
      out.write("</div>\n");
      out.write("<!-- ./wrapper -->\n");
      out.write("\n");
      out.write("<!-- jQuery 3 -->\n");
      out.write("<script src=\"../../bower_components/jquery/dist/jquery.min.js\"></script>\n");
      out.write("<!-- Bootstrap 3.3.7 -->\n");
      out.write("<script src=\"../../bower_components/bootstrap/dist/js/bootstrap.min.js\"></script>\n");
      out.write("<!-- SlimScroll -->\n");
      out.write("<script src=\"../../bower_components/jquery-slimscroll/jquery.slimscroll.min.js\"></script>\n");
      out.write("<!-- FastClick -->\n");
      out.write("<script src=\"../../bower_components/fastclick/lib/fastclick.js\"></script>\n");
      out.write("<!-- AdminLTE App -->\n");
      out.write("<script src=\"../../dist/js/adminlte.min.js\"></script>\n");
      out.write("<!-- AdminLTE for demo purposes -->\n");
      out.write("<script src=\"../../dist/js/demo.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
